spring.application.name=registration
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:postgresql://core-backend-db:5432/car_db
spring.datasource.username=car_user
spring.datasource.password=car_pass
spring.datasource.hikari.initialization-fail-timeout=-1

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/cardpgbackend
frontend.urls=http://localhost,http://localhost:5173

cardpg.engine.base-url=http://geo-calculation-engine-app:8080/api
cardpg.engine.workflow=CAR_DPG
cardpg.engine.timeout.connect-ms=3000
cardpg.engine.timeout.read-ms=60000